import React from "react";

const PrivacyPolicy = () => {
  const styles = {
    container: {
      padding: "20px",
      margin: "0 auto",
    //   maxWidth: "900px",
    width: "80%",
      backgroundColor: "#f9f9f9",
      borderRadius: "8px",
      boxShadow: "0 4px 8px rgba(0, 0, 0, 0.1)",
    },
    header: {
      fontSize: "1.8rem",
      fontWeight: "bold",
      color: "#000",
      marginBottom: "20px",
    },
    titleHeading: {
      fontSize: "2.5rem",
      fontWeight: "bold",
      color: "#000",
      marginBottom: "20px",
    },
    superHeader: {
      fontSize: "1.8rem",
      marginTop: "20px",
      color: "#000",
    },
    subHeader: {
      fontSize: "1.5rem",
      marginTop: "15px",
      color: "#000",
    },
    paragraph: {
      fontSize: "1rem",
      lineHeight: "1.6",
      color: "#000",
      marginBottom: "16px",
    },
    listItem: {
      marginLeft: "20px",
    },
  };

  return (
    <div style={styles.container}>
      <h1 style={styles.titleHeading}>Privacy Policy</h1>
      <p style={styles.paragraph}>
        <strong>Last updated: July 08, 2024</strong>
      </p>
      <p style={styles.paragraph}>
        This Privacy Policy describes Our policies and procedures on the
        collection, use and disclosure of Your information when You use the
        Service and tells You about Your privacy rights and how the law protects
        You.
      </p>

      <h2 style={styles.header}>Interpretation and Definitions</h2>
      <h3 style={styles.subHeader}>Interpretation</h3>
      <p style={styles.paragraph}>
        The words of which the initial letter is capitalized have meanings
        defined under the following conditions. The following definitions shall
        have the same meaning regardless of whether they appear in singular or
        in plural.
      </p>

      <h3 style={styles.subHeader}>Definitions</h3>
      <p style={styles.paragraph}>For the purposes of this Privacy Policy:</p>
      <ul>
        <li style={styles.paragraph}>
          <strong>Account</strong> means a unique account created for You to
          access our Service or parts of our Service.
        </li>
        <li style={styles.paragraph}>
          <strong>Affiliate</strong> means an entity that controls, is
          controlled by or is under common control with a party, where "control"
          means ownership of 50% or more of the shares, equity interest or other
          securities entitled to vote for election of directors or other
          managing authority.
        </li>
        <li style={styles.paragraph}>
          <strong>Company</strong> (referred to as either "the Company", "We",
          "Us" or "Our" in this Agreement) refers to IQPaths, 301/64 Pricanco
          Colony, Indore.
        </li>
        <li style={styles.paragraph}>
          <strong>Cookies</strong> are small files that are placed on Your
          computer, mobile device or any other device by a website, containing
          the details of Your browsing history on that website among its many
          uses.
        </li>
        <li style={styles.paragraph}>
          <strong>Country</strong> refers to: Madhya Pradesh, India.
        </li>
        <li style={styles.paragraph}>
          <strong>Device</strong> means any device that can access the Service
          such as a computer, a cellphone or a digital tablet.
        </li>
        <li style={styles.paragraph}>
          <strong>Personal Data</strong> is any information that relates to an
          identified or identifiable individual.
        </li>
        <li style={styles.paragraph}>
          <strong>Service</strong> refers to the Website.
        </li>
        <li style={styles.paragraph}>
          <strong>Service Provider</strong> means any natural or legal person
          who processes the data on behalf of the Company. It refers to
          third-party companies or individuals employed by the Company to
          facilitate the Service.
        </li>
        <li style={styles.paragraph}>
          <strong>Usage Data</strong> refers to data collected automatically,
          either generated by the use of the Service or from the Service
          infrastructure itself (for example, the duration of a page visit).
        </li>
        <li style={styles.paragraph}>
          <strong>Website</strong> refers to iQpaths, accessible from{" "}
          <a href="https://iqpaths.com/">https://iqpaths.com/</a>.
        </li>
        <li style={styles.paragraph}>
          <strong>You</strong> means the individual accessing or using the
          Service, or the company, or other legal entity on behalf of which such
          individual is accessing or using the Service.
        </li>
      </ul>

      <h2 style={styles.header}>Collecting and Using Your Personal Data</h2>
      <h3 style={styles.subHeader}>Types of Data Collected</h3>
      <h4 style={styles.subHeader}>Personal Data</h4>
      <p style={styles.paragraph}>
        While using Our Service, We may ask You to provide Us with certain
        personally identifiable information that can be used to contact or
        identify You. Personally identifiable information may include, but is
        not limited to:
      </p>
      <ul>
        <li style={styles.paragraph}>Email address</li>
        <li style={styles.paragraph}>First name and last name</li>
        <li style={styles.paragraph}>Phone number</li>
        <li style={styles.paragraph}>Usage Data</li>
      </ul>

      <h4 style={styles.subHeader}>Usage Data</h4>
      <p style={styles.paragraph}>
        Usage Data is collected automatically when using the Service.
      </p>
      <p style={styles.paragraph}>
        Usage Data may include information such as Your Device's Internet
        Protocol address (e.g. IP address), browser type, browser version, the
        pages of our Service that You visit, the time and date of Your visit,
        the time spent on those pages, unique device identifiers and other
        diagnostic data.
      </p>

      <p style={styles.paragraph}>
        When You access the Service by or through a mobile device, We may
        collect certain information automatically, including, but not limited
        to, the type of mobile device You use, Your mobile device unique ID, the
        IP address of Your mobile device, Your mobile operating system, the type
        of mobile Internet browser You use, unique device identifiers and other
        diagnostic data.
      </p>

      <p style={styles.paragraph}>
        We may also collect information that Your browser sends whenever You
        visit our Service or when You access the Service by or through a mobile
        device.
      </p>

      <h2 style={styles.subHeader}>Tracking Technologies and Cookies</h2>
      <p style={styles.paragraph}>
        We use Cookies and similar tracking technologies to track the activity
        on Our Service and store certain information. These include:
      </p>
      <ul>
        <li style={styles.paragraph}>
          <strong>Cookies or Browser Cookies</strong>: A cookie is a small file
          placed on Your Device. You can instruct Your browser to refuse all
          Cookies or to indicate when a Cookie is being sent. However, if You do
          not accept Cookies, You may not be able to use some parts of our
          Service. Unless you have adjusted Your browser setting so that it will
          refuse Cookies, our Service may use Cookies.
        </li>
        <li style={styles.paragraph}>
          <strong>Web Beacons</strong>: Certain sections of our Service and our
          emails may contain small electronic files known as web beacons (also
          referred to as clear gifs, pixel tags, and single-pixel gifs) that
          permit the Company, for example, to count users who have visited those
          pages or opened an email and for other related website statistics (for
          example, recording the popularity of a certain section and verifying
          system and server integrity).
        </li>
      </ul>

      <p style={styles.paragraph}>
        We use both Session and Persistent Cookies for the purposes set out
        below:
      </p>

      <ul>
        <li style={styles.paragraph}>
          <strong>Necessary / Essential Cookies</strong>
          <p style={styles.paragraph}>Type: Session Cookies</p>
          <p style={styles.paragraph}>Administered by: Us</p>
          <p style={styles.paragraph}>
            Purpose: These Cookies are essential to provide You with services
            available through the Website and to enable You to use some of its
            features. They help to authenticate users and prevent fraudulent use
            of user accounts. Without these Cookies, the services that You have
            asked for cannot be provided, and We only use these Cookies to
            provide You with those services.
          </p>
        </li>
        <li style={styles.paragraph}>
          <strong>Cookies Policy / Notice Acceptance Cookies</strong>:
          <p style={styles.paragraph}>Type: Persistent Cookies</p>
          <p style={styles.paragraph}>Administered by: Us</p>
          <p style={styles.paragraph}>
            Purpose: These Cookies identify if users have accepted the use of
            cookies on the Website.
          </p>
        </li>
        <li style={styles.paragraph}>
          <strong>Functionality Cookies</strong>:
          <p style={styles.paragraph}>Type: Persistent Cookies</p>
          <p style={styles.paragraph}>Administered by: Us</p>
          <p style={styles.paragraph}>
            Purpose: hese Cookies allow us to remember choices You make when You
            use the Website, such as remembering your login details or language
            preference. The purpose of these Cookies is to provide You with a
            more personal experience and to avoid You having to re-enter your
            preferences every time You use the Website.
          </p>
        </li>
      </ul>
      <p style={styles.paragraph}>
      For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.
      </p>
    </div>
  );
};

export default PrivacyPolicy;
